kind: ConfigMap
apiVersion: v1
metadata:
  name: ldap-group-syncer
  namespace: ldap-sync
data:
  sync.yaml: |                                 
    kind: LDAPSyncConfig
    apiVersion: v1
    url: ldap://openldap.ldap.svc.cluster.local:389
    insecure: true
    bindDN: cn=admin,dc=your,dc=company,dc=com
    bindPassword:
      file: "/etc/secrets/bindPassword"
    augmentedActiveDirectory:
        groupsQuery:
            baseDN: "ou=OpenShift,ou=Groups,dc=your,dc=company,dc=com"
            scope: sub
            derefAliases: never
            pageSize: 5
        groupUIDAttribute: dn
        groupNameAttributes: [ cn ]
        usersQuery:
            baseDN: "ou=Users,dc=your,dc=company,dc=com"
            scope: sub
            derefAliases: never
            filter: (objectClass=*)
            pageSize: 5
        userNameAttributes: [ uid ] 
        groupMembershipAttributes: [ memberOf ]